---
title: "Se-Sp_analysis"
author: "Mumbua Mutunga"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r, include=FALSE}

# Loading the packages

pacman::p_load(
  rio,
  here,
  sf,
  janitor,
  lubridate,
  epikit,       
  gtsummary,    
  scales,       
  flextable,
  readxl,
  forcats,
  epiR,
  plyr, 
  epitools,
  geepack, 
  marginaleffects,
  ggpubr,
  psych,
  tinytex,
  forester,
  effectsize,
  RColorBrewer,
  apyramid,
  caret,
  patchwork,
  tidyverse
)

```

```{r, include=FALSE}
# Loading the datasets that we need

con_table<- import(here::here("data","clean", "con_table.rds")) #for making the confusion matrix

ct_data <- import(here::here("data", "clean", "ct_data.rds")) # for analysis
ct_data_ <- import(here::here("data", "clean", "ct_data_.rds"))

ct_plot_dt <- import(here::here("data", "clean", "ct_plot_dt.rds"))

combined <- import(here::here("data", "clean", "combined.rds"))

sample_data <- import(here::here("data","clean","sample_data_clean.rds"))

mapping_data <- import(here::here("data","clean","ct_data1.rds"))

makueni_sd <-sample_data |>
  filter(cnty_name %in% "Makueni") |>
  filter(!Latitude %in% c("-1.3950553815811872"))

projcrs <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

makueni_sd <- st_as_sf(x = makueni_sd,                         
           coords = c("Longitude", "Latitude"),
           crs = projcrs)


siaya_sd <-sample_data |>
  filter(cnty_name %in% "Siaya")

siaya_sd <- st_as_sf(x = siaya_sd,                         
           coords = c("Longitude", "Latitude"),
           crs = projcrs)

counties <- st_read(here::here("data","clean","gadm41_KEN_1.shp"))

makueni_map <- st_read(here::here("data","clean","Mkn_subcounties.shp"))
siaya_map <- st_read(here::here("data","clean","Siaya_subcounties.shp"))

chosen <- counties |>
  filter(NAME_1 %in% c("Makueni", "Siaya"))

```

# Se, Sp, NPV, PPV

```{r warning=FALSE, echo=FALSE}

table1 <- matrix(as.numeric(unlist(con_table)),nrow=nrow(con_table)) #converting the dataframe to matrix

rval <- epi.tests(table1, conf.level = 0.95)
print(rval)

x <- matrix(c(90, 6, 2, 14), nrow = 2)
x

confusionMatrix(x, mode = "everything")

```

# PCR +VE and -VE of the relevant variables

```{r warning=FALSE, echo=FALSE}

table_ <- table(ct_data_$lab_diagnostics_pcr, ct_data_$clinical_signs_)

table_

ggplot(ct_plot_dt, aes(clinical_signs_, percentage, fill = lab_diagnostics_pcr)) + 
  geom_bar(stat = 'identity', position = 'dodge') +
  theme_bw()+
  coord_flip() +
  labs(x = "clinical signs", y = "Percentage", fill = "PCR test")

```

```{r warning=FALSE, echo=FALSE, include=FALSE}
# Calculation of risk ratios

rr <- ct_data |>
  select(sample_collection_dt, species, cnty_name, clinical_signs_, lab_diagnostics_pcr, rapid_diagnostic_test, sample_source) |>
  filter(!lab_diagnostics_pcr %in% "") |>
  group_by(species, clinical_signs_) |>
  dplyr::summarise(
    n_cases   = n(),
    rabies_positive = sum(lab_diagnostics_pcr == "Positive", na.rm=T),
    rabies_negative = sum(lab_diagnostics_pcr == "Negative", na.rm=T)) |>
     flextable::qflextable()
  
rr

table_2 <- ct_data |>
  select(sample_collection_dt, species, cnty_name, clinical_signs_, lab_diagnostics_pcr, rapid_diagnostic_test, sample_source) |>
  filter(!lab_diagnostics_pcr %in% "") |>
  group_by(species, clinical_signs_) |>
  dplyr::count() |>
  mutate(n = as.numeric(n)) |>
  pivot_wider( names_from = clinical_signs_, values_from = n
  ) |>
  mutate_at(c(2:14), as.numeric) |>
  mutate_at(vars(Anorexia:Rabid_animal_bite), ~replace(., is.na(.), 0)) |>
  adorn_totals("row") 


```

```{r, include=F}

reg_model <- glm(lab_diagnostics_pcr ~ clinical_signs_ + species + sample_source, family = "binomial", data = ct_data_)

summary(reg_model)


model1 <- glm(lab_diagnostics_pcr ~ clinical_signs_, family = "binomial", data = ct_data_)

model2 <- glm(lab_diagnostics_pcr ~ clinical_signs_ + species, family = "binomial", data = ct_data_)

lmtest::lrtest(model1, model2)

reg_model <- glm(lab_diagnostics_pcr ~ clinical_signs_ + species + sample_source, family = "binomial", data = ct_data_)

summary(reg_model)

## choose a model using forward selection based on AIC
## you can also do "backward" or "both" by adjusting the direction
final_reg_model <- reg_model %>%
  step(direction = "forward", trace = FALSE)

## show results table of final regression 
mv_tab <- tbl_regression(final_reg_model, exponentiate = F)

mv_tab

```

```{r echo=FALSE, fig.height=15, fig.width=20, warning=FALSE}

plot_data <- ct_data |>
  select(sample_collection_dt, species, bar_code, rapid_diagnostic_test, lab_diagnostics_pcr, clinical_signs_) |>
  filter(!lab_diagnostics_pcr %in% "") |>
  mutate(outcome_result =        ifelse(rapid_diagnostic_test==lab_diagnostics_pcr,"Yes","No")) |>
  mutate(test_result = case_when(
    rapid_diagnostic_test == "Positive" & outcome_result == "Yes" ~ "True_Positive",
    rapid_diagnostic_test == "Negative" & outcome_result == "Yes" ~ "True_Negative",
    lab_diagnostics_pcr == "Positive" & outcome_result == "No" ~ "False_Negative",
             TRUE ~ "False_Positive")) |>
  unique() |>
  mutate(classifications = case_when(
    test_result == "True_Positive" ~ 10,
    test_result == "True_Negative" ~ -10,
    test_result == "False_Positive" ~ 1,
    test_result == "False_Negative" ~ -1,
  )) |>
  mutate(FalseNegRate = 3 / (3+70),
         FalsePosRate = 4 / (4+8),
         TrueNegRate = 8 / (4+8),
         TruePosRate = 70 / (3+70)) |>
  mutate(rate = case_when(
      test_result ==  "True_Positive" ~ 0.9589041,
      test_result ==  "True_Negative" ~ 0.6666667,
      test_result ==  "False_Positive" ~ 0.3333333,
      test_result ==  "False_Negative" ~ 0.04109589,
  )) |>
  mutate(deviation = case_when(
      test_result ==  "True_Positive" ~ (1 - 0.9589041),
      test_result ==  "True_Negative" ~ (1 - 0.6666667),
      test_result ==  "False_Positive" ~ (1 - 0.3333333),
      test_result ==  "False_Negative" ~ (1- 0.04109589)))
  
# clinical signs vs test outcome

test <- plot_data <- ct_data |>
  select(sample_collection_dt, species, bar_code, rapid_diagnostic_test, lab_diagnostics_pcr,clinical_signs_ ) |>
  filter(!lab_diagnostics_pcr %in% "") |>
   mutate(outcome_result =        ifelse(rapid_diagnostic_test==lab_diagnostics_pcr,"Yes","No")) |>
  mutate(test_result = case_when(
    rapid_diagnostic_test == "Positive" & outcome_result == "Yes" ~ "True_Positive",
    rapid_diagnostic_test == "Negative" & outcome_result == "Yes" ~ "True_Negative",
    lab_diagnostics_pcr == "Positive" & outcome_result == "No" ~ "False_Negative",
             TRUE ~ "False_Positive")) |>
  mutate(lab_diagnostics_pcr_ = recode(lab_diagnostics_pcr, 
             "Positive" = "1",
             "Negative" = "0")) |>
  mutate(lab_diagnostics_pcr_ = as.factor(lab_diagnostics_pcr_)) |>
  mutate(clinical_signs_ = as.factor(clinical_signs_)) |>
  mutate(test_result = as.factor(test_result)) 

#Correlation between Clinical Signs and RDT Test Result

corr_rdt_cs <- ggplot(test, aes(x = clinical_signs_, fill = test_result)) +
  geom_bar(position = "fill") + 
  labs(
    x = "Clinical Signs",
    y = "Proportion",
    fill = "RDT Result") +
  theme_minimal() +
  coord_flip()+
  scale_fill_brewer(palette = "Set1", direction = -1)+
  theme(text=element_text(size=15))

ggsave("plot1.png", corr_rdt_cs)
       
#Correlation between Clinical Signs and PCR Test Result

corr_pcr_cs <- ggplot(test, aes(x = clinical_signs_, fill = lab_diagnostics_pcr)) +
  geom_bar(position = "fill") + 
  labs(
    x = "Clinical Signs",
    y = "Proportion",
    fill = "PCR Result") +
  theme_minimal() +
  coord_flip()+
  scale_fill_brewer(palette = "Set1", direction = -1)+
  theme(text=element_text(size=15))

ggsave("plot2.png", corr_pcr_cs)

plot1 <-ggarrange(corr_rdt_cs, corr_pcr_cs,nrow = 1, labels = c("A", "B"),
  font.label = list(size = 20,color = "black", align ="hv"))

plot1

ggsave("plot1.png", plot1,
        width = 23.5, height = 16, units = "cm", dpi = 600)
ggsave("plot1.svg", plot1, device = "svg")
```

# Table species vs the symptoms

```{r warning=FALSE, echo=FALSE}

my_table <- flextable(table_2)|>
  fontsize(i = 1, size = 12, part = "header") |> 
  bold(i = 1, bold = TRUE, part = "header") |>
  bold(i = 5, bold = TRUE, part = "body")

my_table

save_as_docx(my_table, path = "my_table.docx")
```

# GLM

```{r, warning=FALSE, echo=FALSE}

model_glm <- ct_data |>
   select(sample_collection_dt, species, cnty_name, sample_source, lab_diagnostics_pcr, rapid_diagnostic_test, clinical_signs_) |>
  filter(!lab_diagnostics_pcr %in% "") |>
  group_by(sample_collection_dt, species, cnty_name, sample_source, lab_diagnostics_pcr, rapid_diagnostic_test, clinical_signs_) |>
  dplyr::count() |>
  pivot_wider(names_from=clinical_signs_, values_from=n) |>
  mutate_at(vars(aggressive:Abnormal_vocalization), ~replace(., is.na(.), 0)) |>
   mutate(lab_diagnostics_pcr = recode(lab_diagnostics_pcr, 
             "Positive" = "1",
             "Negative" = "0")) |>
  mutate(lab_diagnostics_pcr = as.numeric(lab_diagnostics_pcr))


model1 <- glm(lab_diagnostics_pcr ~ aggressive , family = "binomial", data = model_glm)

summary(model1)

model_glm <- model_glm %>%
  droplevels.data.frame() %>%
  mutate(species2 = case_when(species %in% c("Goat", "Cattle", "Sheep") ~ "Ruminants", 
                              TRUE ~ species))

model1 <- glm(lab_diagnostics_pcr ~ aggressive*species2 , family = "binomial", data = model_glm)
summary(model1)

model2 <- glm(lab_diagnostics_pcr ~ biting_objects , family = "binomial", data = model_glm)

summary(model2)

model3 <- glm(lab_diagnostics_pcr ~ excessive_salivation, family = binomial(link = 'logit'), data = model_glm)

summary(model3)

model4 <- glm(lab_diagnostics_pcr ~ running_aimlessly, family = binomial(link = 'logit'), data = model_glm)

summary(model4)

model5 <- glm(lab_diagnostics_pcr ~ biting_objects + aggressive , family = "binomial", data = model_glm)

summary(model5)

saturated_model <- glm(lab_diagnostics_pcr ~ aggressive + biting_objects + excessive_salivation + hydrophobia + running_aimlessly + high_libido + Rabid_animal_bite + paralysis + Anorexia + Diarrhoea + groaning + Abnormal_vocalization, family = binomial(link = 'logit'), data = model_glm)

summary(saturated_model)

# Looking at the interaction between variables that reported high clinical signs

interactive_model <- glm(lab_diagnostics_pcr ~ aggressive * biting_objects * excessive_salivation, family = binomial(link = 'logit'), data = model_glm)

summary(interactive_model)


interactive_model2 <- glm(lab_diagnostics_pcr ~ aggressive * excessive_salivation, family = binomial(link = 'logit'), data = model_glm)

summary(interactive_model2)

```

# Time series

```{r warning=FALSE, echo=FALSE,}

ts_plot <- combined |>
  select(date_collected, county, rapid_diagnostic_test, lab_diagnostics_pcr) |>
  mutate(rapid_diagnostic_test = recode(rapid_diagnostic_test, 
             "Positive " = "Positive")) |>
  filter(!rapid_diagnostic_test %in% "Inconclusive") |>
  group_by(date_collected,county, rapid_diagnostic_test) |>
  dplyr::count()|>
  mutate(rapid_diagnostic_test = as.factor(rapid_diagnostic_test)) |>
  mutate(n = as.numeric(n))

  
# ggplot(ts_plot, aes(x = date_collected, y = n, col = rapid_diagnostic_test)) +
#   geom_line() +
#   #geom_smooth()+
#   scale_x_date(breaks = "3 weeks")+
#   facet_grid(scales = "free")+
#   facet_wrap(~county) +
#   coord_flip()+
#   ylim(0,4)
#     
# 
# ggplot(ts_plot, aes(x=date_collected, y=n, fill = rapid_diagnostic_test))+
#   geom_bar(stat = "identity")+
#   scale_x_date(breaks = "month") +
#   coord_flip()

ggplot(ts_plot, aes(x=date_collected, fill =rapid_diagnostic_test ))+
  geom_histogram(bins=30, colour="white")+
  scale_y_continuous( breaks = seq(from =0, to=20, by=5), expand = c(0,0))+
  scale_x_date(breaks = "month", expand = c(0,0)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=0.5))+
  labs(x= "Sample collection timelines", y = "Number of samples", fill = "RDT outcome")+
  scale_fill_brewer(palette = "Set1", direction = 1)

ggsave("plot3a.png") 

ggplot(ts_plot, aes(x=date_collected, fill =rapid_diagnostic_test ))+
  geom_histogram(bins=30, colour="white")+
  scale_y_continuous( breaks = seq(from =0, to=20, by=5), expand = c(0,0))+
  scale_x_date(breaks = "2 month", expand = c(0,0)) +
  labs(x= "Sample collection timelines", y = "Number of samples", fill = "RDT outcome")+
  scale_fill_brewer(palette = "Set1", direction = 1)+
  facet_wrap(~county,  scales = "free_x")+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=0.5))

ggsave("plot3b.png") 

ts_plot2 <- ts_plot |>
  filter(rapid_diagnostic_test %in% "Positive")

ggplot(ts_plot2, aes(x=date_collected, fill =rapid_diagnostic_test ))+
  geom_histogram(bins=30, colour="white")+
  scale_y_continuous( breaks = seq(from =0, to=20, by=5), expand = c(0,0))+
  scale_x_date(breaks = "month", expand = c(0,0)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=0.5))+
  labs(x= "Sample collection timelines", y = "Number of samples", fill = "RDT outcome")+
  scale_fill_brewer(palette = "Set1", direction = 1)+
  facet_wrap(~county,  scales = "free_x")

ggsave("plot3c.png") 

species <- ct_data |>
  select(species, bar_code, sequence_status) |>
  distinct(species,bar_code, sequence_status) |>
  filter(!sequence_status %in% "")
  

Fig <- ct_data |>
  select(sample_collection_dt, species, cnty_name, clinical_signs_, lab_diagnostics_pcr, rapid_diagnostic_test, sample_source) |>
  filter(!lab_diagnostics_pcr %in% "") |>
  group_by(species, clinical_signs_) |>
  dplyr::count()

Fig_new = Fig
for(i in unique(Fig$clinical_signs_)){
  for(j in unique(Fig$species)){
    if(nrow(Fig[Fig$clinical_signs_ == i &
                     Fig$species == j,]) == 0){
      new_row = data.frame(
                  clinical_signs_ = i, 
                  species = j, 
                  n = 0)
      Fig_new = rbind(Fig_new, new_row)
    }
  }
}

ggplot(data = Fig_new)+
  geom_col(aes(y=n, x = clinical_signs_,fill = species), position = "dodge") +
  labs(x = "Clinical signs", y = "Number", fill="Species")+
  scale_fill_brewer(palette = "Set1")+
  coord_flip()+
  theme_bw()

ggsave("plot4.png")
  
```

# County plots

```{r}

plot5 <- ggplot()+
  geom_sf(data=counties, aes(geometry=geometry), fill="white")+
  geom_sf(data = chosen, aes(geometry=geometry),fill="orange")+
  geom_sf_text(data = chosen, aes(label = NAME_1),size = 3)+
  labs(x="Longitude",y="Latitude")+theme(text=element_text(size=15)) +
  theme(panel.border = element_blank())

ggsave("plot5.png")

```

# data with RDT & clinical signs

```{r echo=FALSE}

new_plan <- test |>
  select(sample_collection_dt, species, clinical_signs_, lab_diagnostics_pcr, rapid_diagnostic_test, test_result) |>
  group_by(species, clinical_signs_,test_result) |>
  dplyr::count()|>
  group_by(test_result) |>
  mutate(cent = (n/ sum(n))*100)

new_plan_zeros = new_plan
for(i in unique(new_plan$clinical_signs_)){
  for(j in unique(new_plan$test_result)){
    if(nrow(new_plan[new_plan$clinical_signs_ == i &
                     new_plan$test_result == j,]) == 0){
      new_row = data.frame(species = NA, 
                  clinical_signs_ = i, 
                  test_result = j, 
                  n = 0,
                  cent = 0)
      new_plan_zeros = rbind(new_plan_zeros, new_row)
    }
  }
}

for(k in 1:nrow(new_plan_zeros)){
  if(new_plan_zeros$test_result[k] == "True_Positive"){
    new_plan_zeros$cent[k] = (new_plan_zeros$n[k]/90)*100

  }
  if(new_plan_zeros$test_result[k] == "False_Positive"){
    new_plan_zeros$cent[k] = (new_plan_zeros$n[k]/6)*100
  }
  if(new_plan_zeros$test_result[k] == "True_Negative"){
    new_plan_zeros$cent[k] = (new_plan_zeros$n[k]/14)*100
  }
  if(new_plan_zeros$test_result[k] == "False_Negative"){
    new_plan_zeros$cent[k] = (new_plan_zeros$n[k]/2)*100
  }
}

new_plan_zeros$test_result <- factor(new_plan_zeros$test_result, levels = c("True_Positive", "False_Positive", "True_Negative",
        "False_Negative" ))

new_plan_zeros$clinical_signs_ <- as.factor(new_plan_zeros$clinical_signs_)

new_plan_zeros$cent <- as.integer(new_plan_zeros$cent)

ggplot(data =new_plan_zeros,aes(x=forcats::fct_infreq(clinical_signs_, cent), y = cent, fill = test_result))+
  geom_col(position = "dodge")+
  scale_fill_manual(values =c("#48A0B2" ,"#5E4FA2","#CCEA9D", "red"))+
  labs(x="Clinical Signs", y= "Percentage", fill="RDT Results")+
  facet_grid(.~test_result, scales = "free_x")+
  theme_bw() +
  coord_flip() +
  ylim(c(0,100))
  

ggsave("plotxx.png")
                              
TP <- new_plan |>
  filter(test_result %in% "True_Positive")

FP <- new_plan |>
  filter(test_result %in% "False_Positive")

TN <- new_plan |>
  filter(test_result %in% "True_Negative")

FN <- new_plan |>
  filter(test_result %in% "False_Negative")

Spectral<-colorRampPalette(brewer.pal(11,"Spectral") )(15)

TP_plot <- ggplot(data = TP)+
  geom_col(aes(x=forcats::fct_infreq(clinical_signs_, n), y=n, fill = clinical_signs_)) +
  labs(x = "Clinical signs", y = "Number", fill="Clinical signs")+
  scale_fill_manual(values =c("#48A0B2" ,"#3E77B5" ,"#5E4FA2", "#FEE899", "#543005", "#c51b7d" ,"#CCEA9D", "#fddbc7", "#6FC5A4", "#9E0142", "#C52C4B" ,"#E25249", "#F57647", "#FBA45C", "#FDCA78"))+
  coord_flip()

FP_plot <- ggplot(data = FP)+
  geom_col(aes(x=forcats::fct_infreq(clinical_signs_, n), y=n, fill = clinical_signs_)) +
  labs(x = "Clinical signs", y = "Number", fill="Clinical signs")+
  scale_fill_manual(values =c("#48A0B2" ,"#3E77B5" ,"#5E4FA2", "#FEE899", "#543005", "#c51b7d" ,"#F57647"))+
  coord_flip()


TN_plot <- ggplot(data = TN)+
  geom_col(aes(x=forcats::fct_infreq(clinical_signs_, n), y=n, fill = clinical_signs_)) +
  labs(x = "Clinical signs", y = "Number", fill="Clinical signs")+
  scale_fill_manual(values =c("#48A0B2" ,"#3E77B5" ,"#5E4FA2", "#543005", "#c51b7d" ,"#CCEA9D", "#fddbc7", "#6FC5A4", "#9E0142" , "#F57647", "#FBA45C"))+
  coord_flip()

FN_plot <- ggplot(data = FN)+
  geom_col(aes(x=forcats::fct_infreq(clinical_signs_, n), y=n, fill = clinical_signs_)) +
  labs(x = "Clinical signs", y = "Number", fill="Clinical signs")+
  scale_fill_manual(values =c("#48A0B2" ,"#3E77B5" ,"#5E4FA2", "#FEE899", "#543005", "#c51b7d" ,"#F57647", "#fddbc7"))+
  coord_flip()

TP_plot
FP_plot
TN_plot
FN_plot

ggsave("TP_plot.png", TP_plot)
ggsave("FP_plot.png", FP_plot)
ggsave("TN_plot.png", TN_plot)
ggsave("FN_plot.png", FN_plot)



```

# Pyramids

```{r}

sample_data <- test |>
  select(clinical_signs_, test_result) |>
  group_by(clinical_signs_,test_result) |>
  dplyr::count() 
  #dplyr::filter(test_result == "True_Positive" | test_result == "False_Positive") 

sample_data <- as.data.frame(sample_data)

mycolors <- c(brewer.pal(name="Dark2", n = 8), brewer.pal(name="Paired", n = 6))

pr <- age_pyramid(sample_data,
  age_group = clinical_signs_,
  split_by = test_result,
  stack_by = clinical_signs_,
  count = n,
  na.rm = TRUE,
  show_midpoint = F,
  vertical_lines = F,
  horizontal_lines = F,
  pyramid = T,
  pal = mycolors
)

pr

ggsave("pyramid.png", pr)

ggplot(data=sample_data,aes(x=as.factor(n),fill=clinical_signs_)) + 
  geom_bar(data=subset(sample_data,test_result=="True_Positive")) + 
  geom_bar(data=subset(sample_data,test_result=="False_Positive"),aes(y=..count..*(-1))) + 
  scale_fill_manual(values = mycolors) + 
  coord_flip()

# library(ggplot2)
# library(lemon)
# 
# ggplot(data = sample_data, mapping = aes(x = ifelse(test = test_result == "False_Positive" , yes = -test_result, no = test_result), y = clinical_signs_, fill = clinical_signs_)) +
#   geom_col() +
#   scale_x_symmetric(labels = abs) +
#   labs(x = "Population")

```

# simple figure

```{r}
sample_data$test_result <- factor(sample_data$test_result, levels = c("True_Positive", "False_Positive", "True_Negative",
        "False_Negative" ))

ggplot(data = sample_data)+
  geom_col(aes(x=forcats::fct_infreq(clinical_signs_, n), y=n, fill = test_result)) +
  labs(x = "Clinical signs", y = "Number", fill="RDT Results")+
  facet_grid(.~test_result, scales = "free_x") +
  theme_bw()+
  coord_flip() +
  #scale_y_continuous(labels = abs) +
  scale_fill_manual(values =c("#48A0B2" ,"#5E4FA2","#CCEA9D", "red"))+
  #scale_y_continuous(breaks = seq(0,70,5)) 
  ylim(c(0,65)) 
  

ggsave("plot6b.png")


ggplot()+
  geom_col(aes(x=n, y = clinical_signs_), fill = "orange", data = sample_data %>% mutate(subset = "True_Positive")) +
  geom_col(aes(x=n, y = clinical_signs_), fill = "orange", data = sample_data %>% filter(test_result == "False_Positive") %>%
            mutate(subset = "False_Positive")) +
  facet_wrap(~ subset, scales = "free_x") +
  geom_col(aes(x=n, y = clinical_signs_), fill = "orange", data = sample_data %>% filter(test_result == "True_Negative") %>%
            mutate(subset = "True_Negative")) +
  facet_wrap(~ subset, scales = "free_x") +
  geom_col(aes(x=n, y = clinical_signs_), fill = "orange", data = sample_data %>% filter(test_result == "False_Negative") %>%
            mutate(subset = "False_Negative")) +
  facet_wrap(~ subset, scales = "free_x") +
  labs(y = "Clinical signs", x = "Number") +
  theme_bw()

ggsave("plot6.png")
  
```

# Mapping animal samples
```{r}

# Makueni

mapping_mkn <- st_as_sf(mapping_data, coords = c('Longitude', 'Latitude')) |>
  filter(cnty_name %in% "Makueni")

st_crs(mapping_mkn) = 4326

plot7 <- ggplot()+
  geom_sf(data=makueni_map, aes(geometry=geometry), fill = "white")+
  geom_sf(data = mapping_mkn, aes(geometry=geometry, col = species),alpha = 0.7) +
  #theme_bw()+
  labs(x="Longitude",y="Latitude")+
  theme(panel.border = element_blank())
  #theme(text=element_text(size=18))

plot7

ggsave("plot7.png")

# Siaya

mapping_siaya <- st_as_sf(mapping_data, coords = c('Longitude', 'Latitude')) |>
  filter(cnty_name %in% "Siaya")

st_crs(mapping_siaya) = 4326

plot8 <- ggplot()+
  geom_sf(data=siaya_map, aes(geometry=geometry), fill = "white")+
  geom_sf(data = mapping_siaya, aes(geometry = geometry, col = species),alpha = 0.7)+
  theme(panel.border = element_blank())+
  #theme_bw()+
  labs(x="Longitude",y="Latitude")
  
  #theme(text=element_text(size=18))
plot8

ggsave("plot8.png")

mapping__ <- mapping_data |>
  filter(!sequence_status %in% NA) |>
  filter(!clinical_signs %in% "0")

arranged_plot <- (plot7 / plot8) | plot5 

ggsave("arranged_plot.png", arranged_plot, width = 18, height = 12)
```

